<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    EveryWorkflow\CoreBundle\EveryWorkflowCoreBundle::class => ['all' => true],
    EveryWorkflow\MongoBundle\EveryWorkflowMongoBundle::class => ['all' => true],
    EveryWorkflow\DataFormBundle\EveryWorkflowDataFormBundle::class => ['all' => true],
    EveryWorkflow\DataGridBundle\EveryWorkflowDataGridBundle::class => ['all' => true],
    EveryWorkflow\EavBundle\EveryWorkflowEavBundle::class => ['all' => true],
    EveryWorkflow\UserBundle\EveryWorkflowUserBundle::class => ['all' => true],
    EveryWorkflow\SettingBundle\EveryWorkflowSettingBundle::class => ['all' => true],
    EveryWorkflow\ScopeBundle\EveryWorkflowScopeBundle::class => ['all' => true],
    EveryWorkflow\ImportExportBundle\EveryWorkflowImportExportBundle::class => ['all' => true],
    EveryWorkflow\DeveloperBundle\EveryWorkflowDeveloperBundle::class => ['all' => true],
    EveryWorkflow\AdminPanelBundle\EveryWorkflowAdminPanelBundle::class => ['all' => true],
    EveryWorkflow\BaseBundle\EveryWorkflowBaseBundle::class => ['all' => true],
    EveryWorkflow\MediaManagerBundle\EveryWorkflowMediaManagerBundle::class => ['all' => true],
    EveryWorkflow\DamBundle\EveryWorkflowDamBundle::class => ['all' => true],
    EveryWorkflow\UrlRewriteBundle\EveryWorkflowUrlRewriteBundle::class => ['all' => true],
    EveryWorkflow\StaticBlockBundle\EveryWorkflowStaticBlockBundle::class => ['all' => true],
    EveryWorkflow\PageBundle\EveryWorkflowPageBundle::class => ['all' => true],
    EveryWorkflow\PageBuilderBundle\EveryWorkflowPageBuilderBundle::class => ['all' => true],
    EveryWorkflow\FrontendBundle\EveryWorkflowFrontendBundle::class => ['all' => true],
    EveryWorkflow\CmsBundle\EveryWorkflowCmsBundle::class => ['all' => true],
    EveryWorkflow\CustomerBundle\EveryWorkflowCustomerBundle::class => ['all' => true],
    EveryWorkflow\CrmBundle\EveryWorkflowCrmBundle::class => ['all' => true],
    EveryWorkflow\CatalogProductBundle\EveryWorkflowCatalogProductBundle::class => ['all' => true],
    EveryWorkflow\CatalogCategoryBundle\EveryWorkflowCatalogCategoryBundle::class => ['all' => true],
    EveryWorkflow\PimBundle\EveryWorkflowPimBundle::class => ['all' => true],
    EveryWorkflow\SalesOrderBundle\EveryWorkflowSalesOrderBundle::class => ['all' => true],
    EveryWorkflow\EcommerceBundle\EveryWorkflowEcommerceBundle::class => ['all' => true],
];
